"""Generate a temperature/pressure sweep driver (bash) and the post-processing
script that averages each finished simulation and builds aggregate plots.

The sweep driver re-uses the *exact* standalone MD python script produced by
``generate_md_python_script``. For every value in the requested range it:

  * creates a folder named ``<var>_<value>`` (e.g. ``temperature_300``),
  * copies the MD script + the structure files into that folder,
  * rewrites the script's SWEEP anchor line with ``sed`` so the swept
    temperature / pressure is used,
  * runs the simulation,
  * post-processes the folder (average structure + aggregate plots),
  * drops a ``.sweep_done`` marker so the run can be resumed.

The driver is meant to live in the *same* folder as the MD python script and
the structure files.
"""


def generate_md_sweep_bash_script(
    sweep_var="temperature",
    start=300.0,
    end=1000.0,
    step=100.0,
    use_last_structure=True,
    avg_fraction=0.5,
    errorbar_mode="std",
    main_script_name="run_md_simulation.py",
    postprocess_script_name="sweep_postprocess.py",
    python_bin="python",
    output_dir="sweep_averages",
):
    """Return the text of the ``run_sweep.sh`` driver script."""

    sweep_var = "temperature" if str(sweep_var).lower().startswith("t") else "pressure"
    use_last = 1 if use_last_structure else 0
    errorbar_mode = errorbar_mode if errorbar_mode in ("std", "sem", "none") else "std"
    var_label = "Temperature (K)" if sweep_var == "temperature" else "Pressure (GPa)"

    script = f"""#!/usr/bin/env bash
# ============================================================================
#  MD {sweep_var.upper()} SWEEP DRIVER
#  Generated by the uMLIP-Interactive app.
#
#  Sweeps {var_label} over a range and runs the standalone MD script
#  '{main_script_name}' once per value. Place this file in the SAME folder as
#  '{main_script_name}' and your structure files (.cif / .vasp / POSCAR*),
#  then run:  bash run_sweep.sh
#
#  Everything is self-contained: the averaging + plotting step is an embedded
#  Python block (heredoc) inside this file — no extra .py file is needed
#  (Python with ASE / numpy / matplotlib must be importable).
#
#  Resumable: folders that already contain a '.sweep_done' marker are skipped.
# ============================================================================
set -uo pipefail

# ----------------------------- USER SETTINGS --------------------------------
SWEEP_VAR="{sweep_var}"          # "temperature" (K) or "pressure" (GPa)
START={start}                    # first value of the sweep
END={end}                        # last value of the sweep
STEP={step}                      # step size (always given as a positive number)

MAIN_SCRIPT="{main_script_name}"
PYTHON_BIN="{python_bin}"
OUTDIR="{output_dir}"            # aggregated averages + plots land here

# 1 = use the LAST MD step structure of the previous value as the initial
#     structure of the next value (chained / annealing style).
# 0 = always start every value from the ORIGINAL input structures.
USE_LAST_STRUCTURE={use_last}

# Fraction (0-1) of the trajectory (taken from the END) used for averaging.
AVG_FRACTION={avg_fraction}

# Error bars on the aggregate plots:
#   "std"  = standard deviation across the averaged frames
#   "sem"  = standard error of the mean (std / sqrt(N))
#   "none" = no error bars
ERRORBAR_MODE="{errorbar_mode}"

# Glob patterns used to find the original structure files.
STRUCT_GLOBS=("*.cif" "*.vasp" "POSCAR*" "*.poscar")
# ----------------------------------------------------------------------------

shopt -s nullglob
BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$BASE_DIR"

resolve_main_script() {{
    # 1) preferred exact name
    if [ -f "$MAIN_SCRIPT" ] && grep -qE '^SWEEP_(TEMPERATURE|PRESSURE_GPA) =' "$MAIN_SCRIPT"; then
        return 0
    fi
    if [ ! -f "$MAIN_SCRIPT" ]; then
        echo "Note: '$MAIN_SCRIPT' not found in $BASE_DIR — searching for a generated MD script..."
    else
        echo "Note: '$MAIN_SCRIPT' has no SWEEP anchor — searching for a generated MD script..."
    fi
    # 2) any *.py that carries the generated SWEEP anchor (a real MD script).
    #    The anchor lines start at column 0 in the MD script; in this bash
    #    driver they are indented inside a sed command, so a saved-as-.py copy
    #    of this driver will NOT match the '^SWEEP_' anchor.
    local cand
    for cand in *.py; do
        [ -e "$cand" ] || continue
        if grep -qE '^SWEEP_(TEMPERATURE|PRESSURE_GPA) =' "$cand"; then
            MAIN_SCRIPT="$cand"
            echo "Found generated MD script (has SWEEP anchor): '$MAIN_SCRIPT'."
            return 0
        fi
    done
    # 3) last resort: a single *.py in the folder (warn loudly).
    local py_candidates=(*.py)
    if [ "${{#py_candidates[@]}}" -eq 0 ]; then
        echo "ERROR: no MD python script found in $BASE_DIR." >&2
        echo "       Generate it from the app (first tab), save it as '$MAIN_SCRIPT'," >&2
        echo "       and place it next to this driver." >&2
        return 1
    fi
    MAIN_SCRIPT="${{py_candidates[0]}}"
    echo "WARNING: no *.py with a SWEEP anchor found; falling back to '$MAIN_SCRIPT'." >&2
    echo "         If that is not your MD script, rename your generated MD script to" >&2
    echo "         '$MAIN_SCRIPT' (it must contain the 'SWEEP_TEMPERATURE = None' line)." >&2
    return 0
}}

if ! resolve_main_script; then
    exit 1
fi

# ---- Build the list of values (handles ascending and descending ranges) ----
VALUES=$("$PYTHON_BIN" - "$START" "$END" "$STEP" <<'PYEOF'
import sys
start, end, step = (float(sys.argv[1]), float(sys.argv[2]), abs(float(sys.argv[3])))
if step == 0:
    print(("%g" % start)); sys.exit(0)
sign = 1.0 if end >= start else -1.0
n = int(round(abs(end - start) / step)) + 1
vals = [start + sign * step * i for i in range(n)]
print(" ".join("%g" % v for v in vals))
PYEOF
)

if [ -z "$VALUES" ]; then
    echo "ERROR: could not build value list from START/END/STEP" >&2
    exit 1
fi

if [ "$USE_LAST_STRUCTURE" -eq 1 ]; then USE_LAST_LABEL="Yes"; else USE_LAST_LABEL="No"; fi
echo "============================================================"
echo " MD sweep over $SWEEP_VAR"
echo " Values: $VALUES"
echo " Use last-step structure as next initial: $USE_LAST_LABEL"
echo " Averaging fraction (tail): $AVG_FRACTION"
echo " Plot error bars: $ERRORBAR_MODE"
echo "============================================================"

mkdir -p "$OUTDIR"

# ---- Copy the initial structures for one value's folder --------------------
copy_initial_structures() {{
    local dest="$1"
    local prev="$2"
    if [ "$USE_LAST_STRUCTURE" -eq 1 ] && [ -n "$prev" ] && [ -d "$prev/md_results" ]; then
        local found=0
        for fvasp in "$prev"/md_results/md_*_final.vasp; do
            [ -e "$fvasp" ] || continue
            local b
            b="$(basename "$fvasp")"
            b="${{b#md_}}"
            b="${{b%_final.vasp}}"
            cp "$fvasp" "$dest/${{b}}.vasp"
            found=1
        done
        if [ "$found" -eq 1 ]; then
            echo "  -> using last-step structures from '$prev'"
            return 0
        fi
        echo "  -> WARNING: no final structures in '$prev', falling back to originals"
    fi
    local any=0
    for pat in "${{STRUCT_GLOBS[@]}}"; do
        for s in $BASE_DIR/$pat; do
            [ -e "$s" ] || continue
            # never copy structures that the driver itself produced
            case "$(basename "$s")" in
                *_final.vasp) continue;;
            esac
            cp "$s" "$dest/"
            any=1
        done
    done
    if [ "$any" -eq 0 ]; then
        echo "  -> ERROR: no original structure files found in $BASE_DIR" >&2
        return 1
    fi
    echo "  -> using original structures"
    return 0
}}

# ---- Copy the MD script into a folder and inject the swept value -----------
prepare_script() {{
    local dest="$1"
    local val="$2"
    cp "$MAIN_SCRIPT" "$dest/$MAIN_SCRIPT"
    if [ "$SWEEP_VAR" = "temperature" ]; then
        sed -i "s|^SWEEP_TEMPERATURE = .*# SWEEP_TEMPERATURE|SWEEP_TEMPERATURE = ${{val}}   # SWEEP_TEMPERATURE|" "$dest/$MAIN_SCRIPT"
    else
        sed -i "s|^SWEEP_PRESSURE_GPA = .*# SWEEP_PRESSURE_GPA|SWEEP_PRESSURE_GPA = ${{val}}   # SWEEP_PRESSURE_GPA|" "$dest/$MAIN_SCRIPT"
    fi
}}

PREV_FOLDER=""
for VAL in $VALUES; do
    FOLDER="${{SWEEP_VAR}}_${{VAL}}"
    echo ""
    echo "------------------------------------------------------------"
    echo " $SWEEP_VAR = $VAL   ->   $FOLDER"
    echo "------------------------------------------------------------"

    if [ -f "$FOLDER/.sweep_done" ]; then
        echo "  Already complete (.sweep_done present) -> skipping."
        PREV_FOLDER="$FOLDER"
        continue
    fi

    # remove any partial/incomplete attempt and start fresh
    rm -rf "$FOLDER"
    mkdir -p "$FOLDER"

    if ! copy_initial_structures "$FOLDER" "$PREV_FOLDER"; then
        echo "  Skipping $VAL (no structures)." >&2
        rm -rf "$FOLDER"
        continue
    fi
    prepare_script "$FOLDER" "$VAL"

    # run the simulation
    ( cd "$FOLDER" && "$BASE_DIR/$PYTHON_BIN" "$MAIN_SCRIPT" 2>&1 | tee md_run.log )
    rc=${{PIPESTATUS[0]}}
    if [ "$rc" -ne 0 ]; then
        echo "  ERROR: MD run for $VAL exited with code $rc. Not marking as done." >&2
        echo "         Fix the issue and re-run run_sweep.sh to resume." >&2
        continue
    fi

    # post-process this folder: average structure + refresh aggregate plots
    # (the Python below is embedded directly in this script as a heredoc)
    "$BASE_DIR/$PYTHON_BIN" - --folder "$FOLDER" --var "$SWEEP_VAR" --value "$VAL" --avg-fraction "$AVG_FRACTION" --errorbar-mode "$ERRORBAR_MODE" --outdir "$OUTDIR" <<'SWEEP_PYEOF'
__SWEEP_POSTPROCESS_PYTHON__
SWEEP_PYEOF
    pp_rc=$?
    if [ "$pp_rc" -ne 0 ]; then
        echo "  WARNING: post-processing (averaging/plots) failed for $VAL" >&2
    fi

    touch "$FOLDER/.sweep_done"
    PREV_FOLDER="$FOLDER"
    echo "  Done: $FOLDER"
done

echo ""
echo "============================================================"
echo " Sweep finished. Aggregated results in: $OUTDIR/"
echo "   - <basename>_averaged_trajectory.xyz   (avg structures vs $SWEEP_VAR)"
echo "   - sweep_summary.csv                     (volume, lattice, energy...)"
echo "   - plots/*.png                           (volume/lattice/energy vs $SWEEP_VAR)"
echo "============================================================"
"""
    # The PYTHON_BIN may legitimately be just "python" (on PATH) rather than a
    # path relative to BASE_DIR. Keep the invocation simple in that common case.
    script = script.replace('"$BASE_DIR/$PYTHON_BIN"', '$PYTHON_BIN')

    # Inject the post-processing Python directly into the heredoc so the whole
    # sweep is a single self-contained run_sweep.sh (no separate .py file).
    postprocess_python = generate_md_sweep_postprocess_script().rstrip("\n")
    script = script.replace("__SWEEP_POSTPROCESS_PYTHON__", postprocess_python)
    return script.strip() + "\n"


def generate_md_sweep_postprocess_script():
    """Return the text of ``sweep_postprocess.py``.

    Called once per finished folder by the sweep driver. It is idempotent: it
    saves a per-folder averaged structure + a small JSON record, then rebuilds
    every aggregate (combined averaged trajectory, summary CSV, plots) from all
    per-folder records found so far. Re-running it never duplicates data.
    """
    return r'''#!/usr/bin/env python
"""Sweep post-processing: average structure + aggregate plots.

Generated by the uMLIP-Interactive app. Invoked by run_sweep.sh after each
folder of a temperature/pressure sweep finishes.

For the just-finished folder it:
  * reads every MD trajectory (md_results/md_*.xyz),
  * averages atomic positions + lattice over the last AVG_FRACTION of frames,
  * writes the averaged structure (POSCAR + xyz) and a JSON record under
    OUTDIR/structures/<basename>/,
then rebuilds the aggregate outputs from ALL records found so far:
  * OUTDIR/<basename>_averaged_trajectory.xyz   (one frame per swept value),
  * OUTDIR/all_averaged_trajectory.xyz,
  * OUTDIR/sweep_summary.csv,
  * OUTDIR/plots/*.png  (volume / lattice / angles / energy vs the swept var).

This script is idempotent, so the whole sweep can be safely resumed.
"""
import os
import sys
import glob
import json
import argparse

import numpy as np

try:
    from ase.io import read, write
    from ase import Atoms
except ImportError:
    print("ERROR: ASE is required for sweep post-processing (pip install ase).")
    sys.exit(1)


def parse_args():
    p = argparse.ArgumentParser(description="Average one sweep folder and rebuild aggregates.")
    p.add_argument("--folder", required=True, help="folder of the finished value")
    p.add_argument("--var", required=True, choices=["temperature", "pressure"])
    p.add_argument("--value", required=True, type=float)
    p.add_argument("--avg-fraction", type=float, default=0.5,
                   help="tail fraction (0-1) of the trajectory used for averaging")
    p.add_argument("--outdir", default="sweep_averages")
    p.add_argument("--errorbar-mode", choices=["std", "sem", "none"], default="std",
                   help="error bars on plots: 'std' = standard deviation, "
                        "'sem' = standard error of the mean (std/sqrt(N)), "
                        "'none' = no error bars")
    return p.parse_args()


def value_tag(v):
    return "%g" % v


def average_one_trajectory(traj_path, frac):
    """Average positions + cell over the last `frac` of frames in a trajectory."""
    frames = read(traj_path, index=":")
    if isinstance(frames, Atoms):
        frames = [frames]
    n = len(frames)
    if n == 0:
        return None
    frac = min(max(frac, 0.0), 1.0)
    start = int(round(n * (1.0 - frac)))
    start = max(0, min(start, n - 1))
    sel = frames[start:]

    positions = np.mean([f.get_positions() for f in sel], axis=0)
    cells = np.array([f.get_cell().array for f in sel])
    avg_cell = np.mean(cells, axis=0)
    vols = np.array([f.get_volume() for f in sel])
    cellpars = np.array([f.cell.cellpar() for f in sel])

    avg = sel[0].copy()
    avg.set_cell(avg_cell, scale_atoms=False)
    avg.set_positions(positions)
    try:
        avg.wrap()
    except Exception:
        pass

    stats = {
        "n_frames_total": n,
        "n_frames_avg": len(sel),
        "volume": float(np.mean(vols)),
        "volume_std": float(np.std(vols)),
    }
    for i, label in enumerate(["a", "b", "c", "alpha", "beta", "gamma"]):
        stats[label] = float(np.mean(cellpars[:, i]))
        stats[label + "_std"] = float(np.std(cellpars[:, i]))
    return avg, stats


def read_csv_means(csv_path, frac):
    """Average the scalar quantities logged by the MD script over the tail."""
    if not os.path.exists(csv_path):
        return {}
    import csv as _csv
    try:
        with open(csv_path) as fh:
            rows = list(_csv.DictReader(fh))
    except Exception:
        return {}
    if not rows:
        return {}
    frac = min(max(frac, 0.0), 1.0)
    start = int(round(len(rows) * (1.0 - frac)))
    start = max(0, min(start, len(rows) - 1))
    sel = rows[start:]
    out = {}
    for key, col in [("Etot", "Etot[eV]"), ("Epot", "Epot[eV]"),
                     ("Ekin", "Ekin[eV]"), ("T", "T[K]"), ("P", "P[GPa]")]:
        vals = []
        for r in sel:
            v = r.get(col)
            if v in (None, "", "nan", "NaN"):
                continue
            try:
                vals.append(float(v))
            except ValueError:
                continue
        if vals:
            out[key] = float(np.mean(vals))
            out[key + "_std"] = float(np.std(vals))
            out["n_csv_avg"] = len(vals)
    return out


def process_folder(args):
    struct_root = os.path.join(args.outdir, "structures")
    os.makedirs(struct_root, exist_ok=True)
    tag = value_tag(args.value)

    trajs = sorted(glob.glob(os.path.join(args.folder, "md_results", "md_*.xyz")))
    if not trajs:
        print("[postproc] no trajectories found in %s/md_results" % args.folder)

    for traj in trajs:
        fn = os.path.basename(traj)
        if fn.startswith("md_") and fn.endswith(".xyz"):
            base = fn[len("md_"):-len(".xyz")]
        else:
            base = os.path.splitext(fn)[0]

        res = average_one_trajectory(traj, args.avg_fraction)
        if res is None:
            print("[postproc] skipping empty trajectory %s" % traj)
            continue
        avg, stats = res

        bdir = os.path.join(struct_root, base)
        os.makedirs(bdir, exist_ok=True)
        avg.info["sweep_var"] = args.var
        avg.info["sweep_value"] = args.value
        try:
            write(os.path.join(bdir, "%s_%s.vasp" % (args.var, tag)), avg, format="vasp")
        except Exception as e:
            print("[postproc] could not write POSCAR for %s: %s" % (base, e))
        write(os.path.join(bdir, "%s_%s.xyz" % (args.var, tag)), avg)

        record = {"basename": base, "var": args.var, "value": args.value,
                  "folder": os.path.abspath(args.folder)}
        record.update(stats)
        record.update(read_csv_means(
            os.path.join(args.folder, "md_results", "md_%s_data.csv" % base),
            args.avg_fraction))
        with open(os.path.join(bdir, "%s_%s.json" % (args.var, tag)), "w") as fh:
            json.dump(record, fh, indent=2)

        print("[postproc] %s: V = %.3f +/- %.3f A^3   (avg of %d/%d frames) at %s = %g"
              % (base, stats["volume"], stats["volume_std"], stats["n_frames_avg"],
                 stats["n_frames_total"], args.var, args.value))


def rebuild_aggregates(outdir, var, errorbar_mode="std"):
    struct_root = os.path.join(outdir, "structures")
    summary_rows = []
    all_frames = []

    for bdir in sorted(glob.glob(os.path.join(struct_root, "*"))):
        if not os.path.isdir(bdir):
            continue
        base = os.path.basename(bdir)
        recs = []
        for jf in glob.glob(os.path.join(bdir, "%s_*.json" % var)):
            try:
                with open(jf) as fh:
                    recs.append(json.load(fh))
            except Exception:
                pass
        recs.sort(key=lambda r: r.get("value", 0.0))

        base_frames = []
        for r in recs:
            summary_rows.append(r)
            xyz = os.path.join(bdir, "%s_%s.xyz" % (var, value_tag(r["value"])))
            if os.path.exists(xyz):
                try:
                    a = read(xyz)
                    a.info["sweep_var"] = var
                    a.info["sweep_value"] = r["value"]
                    base_frames.append(a)
                except Exception:
                    pass
        if base_frames:
            write(os.path.join(outdir, "%s_averaged_trajectory.xyz" % base), base_frames)
            all_frames.extend(base_frames)

    if all_frames:
        write(os.path.join(outdir, "all_averaged_trajectory.xyz"), all_frames)

    write_summary_csv(outdir, summary_rows)
    make_plots(outdir, summary_rows, var, errorbar_mode)
    return summary_rows


def write_summary_csv(outdir, rows):
    if not rows:
        return
    import csv as _csv
    cols = ["basename", "var", "value", "n_frames_total", "n_frames_avg",
            "volume", "volume_std",
            "a", "a_std", "b", "b_std", "c", "c_std",
            "alpha", "alpha_std", "beta", "beta_std", "gamma", "gamma_std",
            "Etot", "Etot_std", "Epot", "Epot_std", "Ekin", "Ekin_std",
            "T", "T_std", "P", "P_std", "folder"]
    extra = sorted({k for r in rows for k in r.keys() if k not in cols})
    cols = cols + extra
    rows_sorted = sorted(rows, key=lambda r: (r.get("basename", ""), r.get("value", 0.0)))
    path = os.path.join(outdir, "sweep_summary.csv")
    with open(path, "w", newline="") as fh:
        w = _csv.DictWriter(fh, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows_sorted:
            w.writerow(r)
    print("[postproc] wrote %s (%d rows)" % (path, len(rows_sorted)))


def make_plots(outdir, rows, var, errorbar_mode="std"):
    if not rows:
        return
    if errorbar_mode not in ("std", "sem", "none"):
        errorbar_mode = "std"
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:
        print("[postproc] matplotlib unavailable, skipping plots: %s" % e)
        return

    # ---- publication-quality global style --------------------------------
    plt.rcParams.update({
        "figure.figsize": (8.0, 6.0),
        "figure.dpi": 120,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans", "Arial", "Helvetica", "Liberation Sans"],
        "mathtext.fontset": "dejavusans",
        "font.size": 16,
        "axes.titlesize": 19,
        "axes.titleweight": "bold",
        "axes.labelsize": 18,
        "axes.labelweight": "bold",
        "axes.linewidth": 1.6,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.major.size": 7,
        "ytick.major.size": 7,
        "xtick.minor.size": 4,
        "ytick.minor.size": 4,
        "xtick.major.width": 1.4,
        "ytick.major.width": 1.4,
        "xtick.top": True,
        "ytick.right": True,
        "legend.fontsize": 14,
        "legend.frameon": True,
        "legend.framealpha": 0.9,
        "legend.edgecolor": "0.3",
        "lines.linewidth": 2.4,
        "lines.markersize": 9,
        "grid.alpha": 0.35,
        "grid.linewidth": 0.9,
    })

    AA = r"$\mathrm{\AA}$"
    AA3 = r"$\mathrm{\AA}^3$"
    DEG = r"$^{\circ}$"
    xlabel = "Temperature (K)" if var == "temperature" else "Pressure (GPa)"
    pdir = os.path.join(outdir, "plots")
    os.makedirs(pdir, exist_ok=True)

    bases = {}
    for r in rows:
        bases.setdefault(r.get("basename", "structure"), []).append(r)

    _marker_kw = dict(marker="o", markeredgecolor="black", markeredgewidth=0.9)
    _err_kw = dict(capsize=4, capthick=1.6, elinewidth=1.6)

    # which per-row sample-count belongs to each metric (for SEM = std/sqrt(N))
    _count_key = {
        "volume": "n_frames_avg", "a": "n_frames_avg", "b": "n_frames_avg",
        "c": "n_frames_avg", "alpha": "n_frames_avg", "beta": "n_frames_avg",
        "gamma": "n_frames_avg", "Etot": "n_csv_avg", "Epot": "n_csv_avg",
        "Ekin": "n_csv_avg", "T": "n_csv_avg", "P": "n_csv_avg",
    }
    _err_note = {"std": r"error bars: $\pm\,1\sigma$ (std. dev.)",
                 "sem": r"error bars: $\pm$ SEM"}.get(errorbar_mode)

    def _finish(ax, ylabel, title, fname, multi=True, has_err=False):
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, which="major")
        ax.minorticks_on()
        ax.tick_params(which="minor", direction="in", top=True, right=True)
        if multi:
            ax.legend(fancybox=False)
        if has_err and _err_note:
            ax.annotate(_err_note, xy=(0.99, 0.01), xycoords="axes fraction",
                        ha="right", va="bottom", fontsize=11, fontstyle="italic",
                        color="0.35")
        plt.tight_layout()
        plt.savefig(os.path.join(pdir, fname))
        plt.close()
        print("[postproc] plot -> %s" % fname)

    def _xy(rs, metric, std_key=None):
        rs = [r for r in rs if r.get(metric) is not None]
        rs.sort(key=lambda r: r["value"])
        x = [r["value"] for r in rs]
        y = [r[metric] for r in rs]
        if not std_key or errorbar_mode == "none":
            return x, y, None
        ckey = _count_key.get(metric)
        err = []
        for r in rs:
            s = r.get(std_key, 0.0) or 0.0
            if errorbar_mode == "sem" and ckey:
                n = r.get(ckey, 0) or 0
                if n and n > 0:
                    s = s / float(np.sqrt(n))
            err.append(s)
        return x, y, err

    def plot_single(metric, ylabel, title, fname, std_key=None):
        fig, ax = plt.subplots()
        plotted = False
        drew_err = False
        for base, rs in sorted(bases.items()):
            x, y, err = _xy(rs, metric, std_key)
            if not x:
                continue
            if err and any(e > 0 for e in err):
                ax.errorbar(x, y, yerr=err, label=base, **_marker_kw, **_err_kw)
                drew_err = True
            else:
                ax.plot(x, y, label=base, **_marker_kw)
            plotted = True
        if not plotted:
            plt.close()
            return
        _finish(ax, ylabel, title, fname, multi=(len(bases) > 1), has_err=drew_err)

    def plot_group(metrics, std_keys, labels, ylabel, title, fname):
        fig, ax = plt.subplots()
        plotted = False
        drew_err = False
        for base, rs in sorted(bases.items()):
            for metric, std_key, mlabel in zip(metrics, std_keys, labels):
                x, y, err = _xy(rs, metric, std_key)
                if not x:
                    continue
                lbl = ("%s: %s" % (base, mlabel)) if len(bases) > 1 else mlabel
                if err and any(e > 0 for e in err):
                    ax.errorbar(x, y, yerr=err, label=lbl, **_marker_kw, **_err_kw)
                    drew_err = True
                else:
                    ax.plot(x, y, label=lbl, **_marker_kw)
                plotted = True
        if not plotted:
            plt.close()
            return
        _finish(ax, ylabel, title, fname, multi=True, has_err=drew_err)

    plot_single("volume", "Average volume (%s)" % AA3,
                "Average volume", "volume_vs_%s.png" % var, "volume_std")
    plot_group(["a", "b", "c"], ["a_std", "b_std", "c_std"],
               ["$a$", "$b$", "$c$"],
               "Lattice length (%s)" % AA, "Lattice parameters",
               "lattice_lengths_vs_%s.png" % var)
    plot_group(["alpha", "beta", "gamma"], ["alpha_std", "beta_std", "gamma_std"],
               [r"$\alpha$", r"$\beta$", r"$\gamma$"],
               "Lattice angle (%s)" % DEG, "Lattice angles",
               "lattice_angles_vs_%s.png" % var)
    plot_single("Etot", "Mean total energy (eV)",
                "Total energy", "energy_total_vs_%s.png" % var, "Etot_std")
    plot_single("Epot", "Mean potential energy (eV)",
                "Potential energy", "energy_potential_vs_%s.png" % var, "Epot_std")
    plot_single("T", "Mean temperature (K)",
                "Mean temperature", "temperature_check_vs_%s.png" % var, "T_std")
    plot_single("P", "Mean pressure (GPa)",
                "Mean pressure", "pressure_vs_%s.png" % var, "P_std")


def main():
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    process_folder(args)
    rebuild_aggregates(args.outdir, args.var, args.errorbar_mode)
    print("[postproc] aggregates updated in %s/" % args.outdir)


if __name__ == "__main__":
    main()
'''
