"""Post-processing scripts panel.

This module powers the "Selected postprocessing scripts" calculation mode in the
main app.  It lets the user pick one of a set of self-contained analysis scripts,
configure it, generate a standalone Python file they can run on their own
machine, and then re-upload the result file produced by that script to explore
it interactively inside the app.

The first available script computes the *average* powder X-ray diffraction (XRD)
pattern from an ASE ``.xyz`` trajectory, while also storing the individual
per-step patterns so the user can scrub through the trajectory or play an
animation here.  The heavy XRD maths uses the Rust-accelerated ``xrd-rust``
package (``pip install xrd-rust``).
"""

import json
import time

import numpy as np
import plotly.graph_objects as go
import streamlit as st


# --------------------------------------------------------------------------- #
#  Available scripts registry
# --------------------------------------------------------------------------- #
XRD_TRAJECTORY_SCRIPT = "Average Powder XRD Pattern from XYZ Trajectory"
AVERAGE_STRUCTURE_SCRIPT = "Average Structure from Trajectory (PBC-aware)"

POSTPROCESSING_SCRIPTS = [
    XRD_TRAJECTORY_SCRIPT,
    AVERAGE_STRUCTURE_SCRIPT,
]


# --------------------------------------------------------------------------- #
#  Standalone-script generation
# --------------------------------------------------------------------------- #
def generate_xrd_trajectory_script(params):
    """Return a standalone Python script (as a string) that computes the
    average powder XRD pattern from an ``.xyz`` trajectory using XRD-Rust.

    ``params`` keys:
        input_dir          : str   - folder scanned for *.xyz trajectories
        two_theta_min      : float
        two_theta_max      : float
        wavelength         : str | float  ("CuKa", "MoKa", ... or a number in Å)
        intensity_mode     : "relative" | "absolute"
        stride             : int   - evaluate every Nth frame
        broaden            : bool  - apply Gaussian broadening (else raw peaks)
        fwhm               : float - Gaussian broadening FWHM (deg 2θ)
        n_points           : int   - points on the common 2θ grid
        num_threads        : int
    """
    traj_dir = params.get("input_dir", ".")
    tt_min = float(params["two_theta_min"])
    tt_max = float(params["two_theta_max"])
    wavelength = params["wavelength"]
    intensity_mode = params.get("intensity_mode", "relative")
    stride = int(params["stride"])
    broaden = bool(params.get("broaden", True))
    fwhm = float(params.get("fwhm", 0.1))
    n_points = int(params.get("n_points", 2000))
    num_threads = int(params.get("num_threads", 4))

    # `wavelength` is either a known string radiation (CuKa, ...) or a float in Å.
    if isinstance(wavelength, str):
        wavelength_repr = repr(wavelength)
    else:
        wavelength_repr = repr(float(wavelength))

    scaled = "True" if intensity_mode == "relative" else "False"
    broaden_repr = "True" if broaden else "False"

    script = f'''#!/usr/bin/env python3
"""
Average powder XRD pattern from an ASE .xyz trajectory (XRD-Rust accelerated).

This script was generated by the MACE-MD GUI.

It processes EVERY `*.xyz` trajectory found in a folder (the current folder by
default). For each trajectory it reads every {stride}-th frame, computes the
powder XRD pattern of each selected frame with the Rust-accelerated `xrd-rust`
package, and writes the results into a dedicated sub-folder named after that
trajectory. For each trajectory it then:

  * saves the individual per-step patterns (raw discrete peaks, and -- when
    broadening is enabled -- the broadened profile),
  * saves the average pattern over all evaluated frames,
  * saves a single animation file `xrd_trajectory_animation.json` that you can
    upload back into the GUI to scrub through the steps or play an animation.

When BROADEN is True the discrete reflections are convolved with a Gaussian
onto a common 2-theta grid. When BROADEN is False the raw discrete peaks are
kept and the GUI draws them as vertical stick lines.

REQUIREMENTS
------------
    pip install xrd-rust ase pymatgen numpy matplotlib

(`xrd-rust` provides the `xrd_rust_calculator.XRDCalculatorRust` class, a
drop-in Rust-accelerated replacement for pymatgen's XRDCalculator. `matplotlib`
is optional -- it is only used to save the publication-ready average plot.)

USAGE
-----
    python {{this_script}}.py                  # all *.xyz in the current folder
    python {{this_script}}.py path/to/folder   # all *.xyz in that folder
    python {{this_script}}.py a.xyz b.xyz       # only the listed trajectories
"""

import os
import sys
import glob
import json

import numpy as np
from ase.io import read
from pymatgen.io.ase import AseAtomsAdaptor

try:
    import matplotlib
    matplotlib.use("Agg")  # headless: just save image files, no display needed
    import matplotlib.pyplot as plt
    HAVE_MPL = True
except ImportError:
    HAVE_MPL = False

try:
    from xrd_rust_calculator import XRDCalculatorRust
except ImportError as exc:
    raise SystemExit(
        "Could not import 'xrd_rust_calculator'.\\n"
        "Install the Rust-accelerated XRD package first:\\n\\n"
        "    pip install xrd-rust\\n"
    ) from exc


# ----------------------------- configuration ------------------------------ #
# Folder scanned for *.xyz trajectories when no file is given on the command
# line. Each trajectory's results go to OUTPUT_DIR/<trajectory-name>/.
INPUT_DIR       = {traj_dir!r}
OUTPUT_DIR      = "xrd_trajectory_results"

WAVELENGTH      = {wavelength_repr}     # "CuKa"/"MoKa"/... or a float in Angstrom
TWO_THETA_RANGE = ({tt_min}, {tt_max})  # degrees
INTENSITY_MODE  = {intensity_mode!r}    # "relative" (max -> 100) or "absolute"
STRIDE          = {stride}              # evaluate every STRIDE-th frame
BROADEN         = {broaden_repr}             # True: Gaussian profile; False: raw stick peaks
FWHM            = {fwhm}                # Gaussian broadening FWHM in degrees 2-theta (used if BROADEN)
N_POINTS        = {n_points}            # points on the common 2-theta grid (used if BROADEN)
NUM_THREADS     = {num_threads}

SCALED          = {scaled}              # passed to get_pattern(scaled=...)
# -------------------------------------------------------------------------- #


def gaussian_broaden(grid, peak_positions, peak_intensities, fwhm):
    """Sum Gaussians (one per reflection) onto a common 2-theta grid."""
    profile = np.zeros_like(grid, dtype=float)
    if len(peak_positions) == 0:
        return profile
    sigma = fwhm / (2.0 * np.sqrt(2.0 * np.log(2.0)))
    inv_two_sigma_sq = 1.0 / (2.0 * sigma * sigma)
    for pos, inten in zip(peak_positions, peak_intensities):
        profile += inten * np.exp(-((grid - pos) ** 2) * inv_two_sigma_sq)
    return profile


def accumulate_sticks(grid, peak_positions, peak_intensities):
    """Deposit each raw peak onto its nearest grid point. Used (only) to build a
    well-defined *average* over frames whose peaks sit at shifting positions."""
    profile = np.zeros_like(grid, dtype=float)
    if len(peak_positions) == 0:
        return profile
    idx = np.searchsorted(grid, peak_positions)
    idx = np.clip(idx, 0, len(grid) - 1)
    for j, inten in zip(idx, peak_intensities):
        profile[j] += inten
    return profile


def save_average_plot(grid, average, out_dir, name):
    """Save a publication-ready figure of the averaged pattern (PNG + PDF)."""
    if not HAVE_MPL:
        print("  [skip] matplotlib not installed - no average plot "
              "(pip install matplotlib).")
        return

    intensity_label = ("Relative intensity (a.u.)"
                       if INTENSITY_MODE == "relative" else "Intensity (a.u.)")
    wl = (f"{{WAVELENGTH}}" if isinstance(WAVELENGTH, str)
          else f"lambda = {{WAVELENGTH:.4f}} A")

    # Publication-style rcParams: clean serif-free fonts, sensible sizes.
    plt.rcParams.update({{
        "font.family": "DejaVu Sans",
        "font.size": 14,
        "axes.linewidth": 1.2,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.major.size": 6,
        "ytick.major.size": 6,
        "xtick.minor.size": 3,
        "ytick.minor.size": 3,
        "legend.frameon": False,
    }})

    fig, ax = plt.subplots(figsize=(8, 5))

    if BROADEN:
        ax.plot(grid, average, color="#1f3a93", lw=1.8)
        ax.fill_between(grid, average, color="#1f3a93", alpha=0.10)
    else:
        # Average of stick spectra -> draw stems at the populated grid points.
        nz = np.where(average > 0)[0]
        ax.vlines(grid[nz], 0.0, average[nz], color="#1f3a93", lw=1.2)

    ax.set_xlim(grid.min(), grid.max())
    ax.set_ylim(bottom=0.0)
    ax.set_xlabel(r"2$\\theta$ (degrees)", fontsize=16)
    ax.set_ylabel(intensity_label, fontsize=16)
    ax.set_title(f"Average powder XRD - {{name}}", fontsize=16, pad=10)
    ax.minorticks_on()
    ax.tick_params(which="both", top=True, right=True, labelsize=13)

    ax.text(0.97, 0.95, wl, transform=ax.transAxes, ha="right", va="top",
            fontsize=12, color="#444")

    fig.tight_layout()
    png = os.path.join(out_dir, "average_pattern.png")
    pdf = os.path.join(out_dir, "average_pattern.pdf")
    fig.savefig(png, dpi=600, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")          # vector copy for journals
    plt.close(fig)
    print(f"  average plot    -> {{png}} (+ .pdf)")


def format_hkl(hkls_for_peak):
    """Return e.g. '(1,-2,0)' for one reflection, or '(1,-2,0);(2,0,0)' when
    several reflections overlap at the same 2-theta -- no surrounding list []."""
    parts = []
    for h in hkls_for_peak:
        parts.append("(" + ",".join(str(v) for v in tuple(h["hkl"])) + ")")
    return ";".join(parts)


def process_trajectory(traj_path, calc, adaptor, grid):
    """Compute and write all XRD results for a single trajectory file."""
    name = os.path.splitext(os.path.basename(traj_path))[0]
    out_dir = os.path.join(OUTPUT_DIR, name)
    steps_dir = os.path.join(out_dir, "per_step_patterns")
    os.makedirs(steps_dir, exist_ok=True)

    print(f"\\nTrajectory: {{traj_path}}  ->  {{out_dir}}/")
    frames = read(traj_path, index=":")
    n_frames = len(frames)
    print(f"  {{n_frames}} frames found; evaluating every {{STRIDE}}-th frame.")

    # Actual 0-based trajectory frame indices we evaluate (e.g. 0, 10, 20, ...).
    selected_indices = list(range(0, n_frames, STRIDE))
    if not selected_indices:
        print("  [skip] no frames selected - check STRIDE.")
        return

    grid_accum = []          # per-frame profile on the common grid (for the average)
    frame_payload = []       # what gets stored per step in the animation file
    evaluated_steps = []

    for frame_idx in selected_indices:
        atoms = frames[frame_idx]
        if atoms.cell is None or atoms.cell.rank < 3:
            print(f"  [skip] frame {{frame_idx}} has no 3-D cell; "
                  "powder XRD needs a periodic cell.")
            continue

        structure = adaptor.get_structure(atoms)
        pattern = calc.get_pattern(
            structure, scaled=SCALED, two_theta_range=TWO_THETA_RANGE
        )

        peak_x = np.asarray(pattern.x, dtype=float)
        peak_y = np.asarray(pattern.y, dtype=float)

        # Per-frame relative normalisation acts on the raw peaks first.
        if INTENSITY_MODE == "relative" and peak_y.size and peak_y.max() > 0:
            peak_y = peak_y / peak_y.max() * 100.0

        if BROADEN:
            profile = gaussian_broaden(grid, peak_x, peak_y, FWHM)
            if INTENSITY_MODE == "relative" and profile.max() > 0:
                profile = profile / profile.max() * 100.0
            grid_accum.append(profile)
            frame_payload.append(profile.tolist())
            # Save the broadened profile for this step.
            prof_csv = os.path.join(steps_dir, f"step_{{frame_idx:06d}}_profile.csv")
            np.savetxt(
                prof_csv, np.column_stack([grid, profile]),
                delimiter=",", header="2theta,intensity", comments="",
            )
        else:
            grid_accum.append(accumulate_sticks(grid, peak_x, peak_y))
            frame_payload.append({{"x": peak_x.tolist(), "y": peak_y.tolist()}})

        evaluated_steps.append(frame_idx)

        # Always save the raw discrete peaks for this step (2theta, I, hkl, mult).
        step_csv = os.path.join(steps_dir, f"step_{{frame_idx:06d}}_peaks.csv")
        with open(step_csv, "w") as fh:
            fh.write("2theta,intensity,hkl,multiplicity\\n")
            for i in range(len(peak_x)):
                try:
                    hkl_str = format_hkl(pattern.hkls[i])
                    mult = sum(h["multiplicity"] for h in pattern.hkls[i])
                except (TypeError, KeyError, IndexError):
                    hkl_str, mult = "", 0
                fh.write(f"{{peak_x[i]}},{{peak_y[i]}},\\"{{hkl_str}}\\",{{mult}}\\n")

        print(f"  frame {{frame_idx}}: {{len(peak_x)}} reflections")

    if not evaluated_steps:
        print("  [skip] no frame could be evaluated (no periodic cells?).")
        return

    grid_accum = np.array(grid_accum)
    average = grid_accum.mean(axis=0)
    if INTENSITY_MODE == "relative" and average.max() > 0:
        average = average / average.max() * 100.0

    # Average pattern CSV.
    avg_csv = os.path.join(out_dir, "average_pattern.csv")
    np.savetxt(
        avg_csv, np.column_stack([grid, average]),
        delimiter=",", header="2theta,intensity", comments="",
    )
    print(f"  average pattern -> {{avg_csv}}")

    # Publication-ready figure of the average pattern (PNG + PDF).
    save_average_plot(grid, average, out_dir, name)

    # Animation file consumed by the GUI viewer.
    animation = {{
        "type": "xrd_trajectory_animation",
        "representation": "broadened" if BROADEN else "sticks",
        "metadata": {{
            "trajectory_file": os.path.basename(traj_path),
            "wavelength": WAVELENGTH,
            "two_theta_range": list(TWO_THETA_RANGE),
            "intensity_mode": INTENSITY_MODE,
            "stride": STRIDE,
            "broaden": BROADEN,
            "fwhm": FWHM,
            "n_points": N_POINTS,
            "n_frames_total": n_frames,
            "n_frames_evaluated": len(evaluated_steps),
        }},
        "two_theta": grid.tolist(),
        "steps": evaluated_steps,                 # e.g. [0, 10, 20, 30, ...]
        # broadened -> list of profile arrays on `two_theta`;
        # sticks    -> list of {{"x": [...], "y": [...]}} raw peaks per step.
        "frames": frame_payload,
        "average": average.tolist(),              # always a grid profile
    }}
    anim_path = os.path.join(out_dir, "xrd_trajectory_animation.json")
    with open(anim_path, "w") as fh:
        json.dump(animation, fh)
    print(f"  animation file -> {{anim_path}}")


def main():
    # Resolve the list of trajectories to process.
    args = sys.argv[1:]
    traj_files = []
    if args:
        for a in args:
            if os.path.isdir(a):
                traj_files += sorted(glob.glob(os.path.join(a, "*.xyz")))
            else:
                traj_files.append(a)
    else:
        traj_files = sorted(glob.glob(os.path.join(INPUT_DIR, "*.xyz")))

    if not traj_files:
        raise SystemExit("No .xyz trajectory files found to process.")

    print(f"Found {{len(traj_files)}} trajectory file(s) to process:")
    for t in traj_files:
        print(f"  - {{t}}")

    grid = np.linspace(TWO_THETA_RANGE[0], TWO_THETA_RANGE[1], N_POINTS)
    calc = XRDCalculatorRust(
        wavelength=WAVELENGTH, symprec=0,
        parallel=True, num_threads=NUM_THREADS, use_simd=True,
    )
    adaptor = AseAtomsAdaptor()

    for traj_path in traj_files:
        if not os.path.exists(traj_path):
            print(f"\\n[skip] file not found: {{traj_path}}")
            continue
        process_trajectory(traj_path, calc, adaptor, grid)

    print("\\nDone. Each trajectory's results are in "
          f"'{{OUTPUT_DIR}}/<trajectory-name>/'.")
    print("Upload a trajectory's 'xrd_trajectory_animation.json' back into the "
          "GUI (Selected postprocessing scripts) to scrub through steps or "
          "play the animation.")


if __name__ == "__main__":
    main()
'''
    return script


def generate_average_structure_script(params):
    """Return a standalone Python script (as a string) that computes the
    PBC-aware average structure from each ``.xyz`` trajectory in a folder.

    ``params`` keys:
        input_dir     : str   - folder scanned for *.xyz trajectories
        stride        : int   - average every Nth frame
        skip_initial  : int   - number of initial frames to skip (equilibration)
        wrap          : bool   - wrap atoms back into the averaged cell (PBC)
        formats       : list[str] subset of {"cif", "vasp", "xyz"}
    """
    traj_dir = params.get("input_dir", ".")
    stride = int(params.get("stride", 1))
    skip_initial = int(params.get("skip_initial", 0))
    wrap = bool(params.get("wrap", True))
    formats = list(params.get("formats", ["cif", "vasp", "xyz"]))

    script = f'''#!/usr/bin/env python3
"""
Average structure from ASE .xyz trajectories (PBC-aware).

This script was generated by the MACE-MD GUI.

It processes EVERY `*.xyz` trajectory found in a folder (the current folder by
default). For each trajectory it:

  * averages the lattice parameters (a, b, c, alpha, beta, gamma) over the
    selected frames and rebuilds the average cell from them,
  * averages the atomic positions using a periodic (circular) mean of the
    fractional coordinates, so atoms that cross a periodic boundary between
    frames are averaged correctly,
  * (optionally) wraps every atom back inside the averaged cell,
  * writes the average structure to the requested file formats and a
    `average_lattice.txt` summary (mean +/- std of each lattice parameter).

Results for each trajectory go to a dedicated sub-folder named after it:
`average_structure_results/<trajectory-name>/`.

WHY A CIRCULAR MEAN?
--------------------
A plain Cartesian average of positions is wrong under PBC: an atom oscillating
around a cell face may appear near frac=0.0 in some frames and frac=0.99 in
others; the arithmetic mean (~0.5) would place it on the wrong side. Averaging
the unit vectors (cos/sin of 2*pi*frac) and converting back gives the correct
periodic mean.

REQUIREMENTS
------------
    pip install ase numpy

USAGE
-----
    python {{this_script}}.py                  # all *.xyz in the current folder
    python {{this_script}}.py path/to/folder   # all *.xyz in that folder
    python {{this_script}}.py a.xyz b.xyz       # only the listed trajectories
"""

import os
import sys
import glob

import numpy as np
from ase.io import read, write
from ase import Atoms
from ase.geometry import cellpar_to_cell


# ----------------------------- configuration ------------------------------ #
INPUT_DIR     = {traj_dir!r}
OUTPUT_DIR    = "average_structure_results"

STRIDE        = {stride}          # average every STRIDE-th frame
SKIP_INITIAL  = {skip_initial}    # skip this many initial frames (equilibration)
WRAP          = {wrap!r}          # wrap atoms back into the averaged cell (PBC)
FORMATS       = {formats!r}       # any of: "cif", "vasp", "xyz"
# -------------------------------------------------------------------------- #

# Map our format keys to (filename, ase-write-kwargs).
_FORMAT_MAP = {{
    "cif":  ("average_structure.cif",  {{"format": "cif"}}),
    "vasp": ("average_structure.vasp", {{"format": "vasp", "sort": True}}),
    "xyz":  ("average_structure.xyz",  {{"format": "extxyz"}}),
}}


def circular_mean_frac(fracs):
    """Periodic mean of fractional coordinates, shape (nframes, natoms, 3)."""
    angles = 2.0 * np.pi * fracs
    mean_cos = np.cos(angles).mean(axis=0)
    mean_sin = np.sin(angles).mean(axis=0)
    mean_angle = np.arctan2(mean_sin, mean_cos)
    return (mean_angle / (2.0 * np.pi)) % 1.0


def average_one(traj_path):
    name = os.path.splitext(os.path.basename(traj_path))[0]
    out_dir = os.path.join(OUTPUT_DIR, name)
    os.makedirs(out_dir, exist_ok=True)

    print(f"\\nTrajectory: {{traj_path}}  ->  {{out_dir}}/")
    frames = read(traj_path, index=":")
    n_total = len(frames)
    sel = frames[SKIP_INITIAL::STRIDE]
    if not sel:
        print("  [skip] no frames selected - check STRIDE / SKIP_INITIAL.")
        return
    print(f"  {{n_total}} frames; averaging {{len(sel)}} of them "
          f"(skip first {{SKIP_INITIAL}}, every {{STRIDE}}-th).")

    ref = sel[0]
    n_atoms = len(ref)
    symbols = ref.get_chemical_symbols()

    # Consistency check: same atom count and ordering across all used frames.
    for k, f in enumerate(sel):
        if len(f) != n_atoms or f.get_chemical_symbols() != symbols:
            print(f"  [skip] frame {{k}} has a different atom count/order; "
                  "cannot average a trajectory whose composition changes.")
            return
        if f.cell is None or f.cell.rank < 3:
            print(f"  [skip] frame {{k}} has no 3-D cell; PBC averaging needs "
                  "a periodic cell.")
            return

    # Average lattice parameters and rebuild the average cell from them.
    cellpars = np.array([f.cell.cellpar() for f in sel])   # (nframes, 6)
    avg_cellpar = cellpars.mean(axis=0)
    std_cellpar = cellpars.std(axis=0)
    avg_cell = cellpar_to_cell(avg_cellpar)

    # Periodic (circular) mean of the (wrapped) fractional coordinates.
    fracs = np.array([f.get_scaled_positions(wrap=True) for f in sel])
    avg_frac = circular_mean_frac(fracs)

    avg = Atoms(symbols=symbols, scaled_positions=avg_frac,
                cell=avg_cell, pbc=True)
    if WRAP:
        avg.wrap()

    # Write the requested structure files.
    written = []
    for key in FORMATS:
        if key not in _FORMAT_MAP:
            print(f"  [warn] unknown format '{{key}}' - skipped.")
            continue
        fname, kw = _FORMAT_MAP[key]
        path = os.path.join(out_dir, fname)
        write(path, avg, **kw)
        written.append(path)
        print(f"  structure      -> {{path}}")

    # Lattice-parameter summary.
    labels = ["a (A)", "b (A)", "c (A)",
              "alpha (deg)", "beta (deg)", "gamma (deg)"]
    vols = np.array([f.get_volume() for f in sel])
    summary = os.path.join(out_dir, "average_lattice.txt")
    with open(summary, "w") as fh:
        fh.write(f"# Average structure for trajectory: {{os.path.basename(traj_path)}}\\n")
        fh.write(f"# frames averaged: {{len(sel)}} "
                 f"(of {{n_total}}; skip_initial={{SKIP_INITIAL}}, stride={{STRIDE}})\\n")
        fh.write(f"# atoms: {{n_atoms}}\\n")
        fh.write("# parameter: mean +/- std (sample fluctuation across frames)\\n")
        for lab, m, s in zip(labels, avg_cellpar, std_cellpar):
            fh.write(f"{{lab:>12s}} : {{m:12.5f}} +/- {{s:10.5f}}\\n")
        fh.write(f"{{'volume (A^3)':>12s}} : "
                 f"{{vols.mean():12.5f}} +/- {{vols.std():10.5f}}\\n")
    print(f"  lattice summary -> {{summary}}")
    print(f"  averaged a,b,c = {{avg_cellpar[0]:.4f}}, {{avg_cellpar[1]:.4f}}, "
          f"{{avg_cellpar[2]:.4f}} A ; "
          f"alpha,beta,gamma = {{avg_cellpar[3]:.3f}}, {{avg_cellpar[4]:.3f}}, "
          f"{{avg_cellpar[5]:.3f}} deg")


def main():
    args = sys.argv[1:]
    traj_files = []
    if args:
        for a in args:
            if os.path.isdir(a):
                traj_files += sorted(glob.glob(os.path.join(a, "*.xyz")))
            else:
                traj_files.append(a)
    else:
        traj_files = sorted(glob.glob(os.path.join(INPUT_DIR, "*.xyz")))

    if not traj_files:
        raise SystemExit("No .xyz trajectory files found to process.")

    print(f"Found {{len(traj_files)}} trajectory file(s) to process:")
    for t in traj_files:
        print(f"  - {{t}}")

    for traj_path in traj_files:
        if not os.path.exists(traj_path):
            print(f"\\n[skip] file not found: {{traj_path}}")
            continue
        average_one(traj_path)

    print("\\nDone. Each trajectory's average structure is in "
          f"'{{OUTPUT_DIR}}/<trajectory-name>/'.")


if __name__ == "__main__":
    main()
'''
    return script


# --------------------------------------------------------------------------- #
#  Interactive viewer for the re-uploaded animation file
# --------------------------------------------------------------------------- #
def _load_animation_json(upload):
    if upload is None:
        return None
    try:
        data = json.load(upload)
    except Exception as exc:  # noqa: BLE001
        st.error(f"Could not parse the uploaded JSON file: {exc}")
        return None
    if data.get("type") != "xrd_trajectory_animation":
        st.error(
            "This does not look like an `xrd_trajectory_animation.json` file "
            "produced by the generated script."
        )
        return None
    return data


def _stick_xy(peak_x, peak_y):
    """Build x/y arrays that draw each peak as a vertical line from 0 to its
    intensity, using None separators so one Scatter trace renders all sticks."""
    xs, ys = [], []
    for px, py in zip(peak_x, peak_y):
        xs.extend([px, px, None])
        ys.extend([0.0, py, None])
    return xs, ys


def render_xrd_animation_viewer():
    """Upload an `xrd_trajectory_animation.json` and explore it: scrub through
    the trajectory steps or play an animation of the powder pattern."""
    st.markdown("### 📈 Visualise a trajectory XRD result")
    st.caption(
        "Upload the `xrd_trajectory_animation.json` produced by the generated "
        "script to scrub through the individual trajectory-step patterns or "
        "play an animation. The average pattern can be overlaid as a reference."
    )

    upload = st.file_uploader(
        "Upload `xrd_trajectory_animation.json`",
        type=["json"],
        key="xrd_animation_upload",
    )

    data = _load_animation_json(upload)
    if data is None:
        return

    meta = data.get("metadata", {})
    representation = data.get("representation", "broadened")
    is_sticks = representation == "sticks"
    two_theta = np.asarray(data["two_theta"], dtype=float)
    steps = list(data["steps"])
    raw_frames = data["frames"]
    average = np.asarray(data["average"], dtype=float)

    intensity_label = (
        "Relative intensity (max = 100)"
        if meta.get("intensity_mode") == "relative"
        else "Absolute intensity"
    )

    info_cols = st.columns(5)
    info_cols[0].metric("Evaluated steps", f"{len(steps)}")
    info_cols[1].metric("Wavelength", str(meta.get("wavelength", "—")))
    info_cols[2].metric("Stride", str(meta.get("stride", "—")))
    tt_range = meta.get("two_theta_range", [two_theta.min(), two_theta.max()])
    info_cols[3].metric("2θ range (°)", f"{tt_range[0]:g}–{tt_range[1]:g}")
    info_cols[4].metric("Peaks", "Sticks" if is_sticks else "Broadened")

    st.caption(
        f"Trajectory steps recorded in this file: "
        f"{', '.join(str(s) for s in steps[:12])}"
        f"{' …' if len(steps) > 12 else ''}"
    )

    view_cols = st.columns([1, 1])
    with view_cols[0]:
        overlay_avg = st.checkbox(
            "Overlay average pattern", value=True, key="xrd_overlay_avg"
        )
    with view_cols[1]:
        mode = st.radio(
            "View mode",
            ["Single step", "Play animation"],
            horizontal=True,
            key="xrd_view_mode",
        )

    # Per-frame y for axis scaling, plus a trace builder per representation.
    if is_sticks:
        frame_max = max(
            (max(fr["y"]) if fr["y"] else 0.0) for fr in raw_frames
        ) if raw_frames else 0.0
    else:
        frame_max = max((max(fr) if fr else 0.0) for fr in raw_frames) if raw_frames else 0.0
    y_max = float(max(frame_max, average.max() if average.size else 0.0)) * 1.05 or 1.0

    # Bigger fonts everywhere on the pattern plots.
    base_font = dict(family="Arial", size=18, color="#1a1a1a")
    title_font = dict(size=26)
    axis_title_font = dict(size=22)
    tick_font = dict(size=17)
    legend_font = dict(size=17)

    def _apply_layout(fig, title, height=520, extra=None):
        layout = dict(
            font=base_font,
            title=dict(text=title, font=title_font, x=0.5, xanchor="center"),
            xaxis=dict(
                title=dict(text="2θ (degrees)", font=axis_title_font),
                tickfont=tick_font,
            ),
            yaxis=dict(
                title=dict(text=intensity_label, font=axis_title_font),
                tickfont=tick_font,
                range=[0, y_max],
            ),
            legend=dict(font=legend_font),
            height=height,
            hovermode="x unified",
        )
        if extra:
            layout.update(extra)
        fig.update_layout(**layout)

    def _pattern_trace(idx, name):
        """A single Scatter trace for trajectory frame `idx`."""
        if is_sticks:
            fr = raw_frames[idx]
            xs, ys = _stick_xy(fr["x"], fr["y"])
            return go.Scatter(
                x=xs, y=ys, mode="lines", name=name,
                line=dict(color="#2563eb", width=1.5),
                connectgaps=False,
            )
        return go.Scatter(
            x=two_theta, y=raw_frames[idx], mode="lines", name=name,
            line=dict(color="#2563eb", width=2),
        )

    avg_trace = go.Scatter(
        x=two_theta, y=average, mode="lines", name="Average",
        line=dict(color="#dc2626", width=1.5, dash="dash"),
    )

    def _single_step_fig(idx):
        fig = go.Figure()
        fig.add_trace(_pattern_trace(idx, f"Step {steps[idx]}"))
        if overlay_avg:
            fig.add_trace(avg_trace)
        _apply_layout(
            fig, f"Powder XRD — trajectory step {steps[idx]}", height=500
        )
        return fig

    if mode == "Single step":
        # Scrub through steps with a slider labelled by the real trajectory step.
        sel_step = st.select_slider(
            "Trajectory step",
            options=steps,
            value=steps[0],
            key="xrd_step_slider",
        )
        st.plotly_chart(_single_step_fig(steps.index(sel_step)),
                        use_container_width=True)

    else:
        anim_cols = st.columns([1, 1])
        with anim_cols[0]:
            loop = st.checkbox(
                "🔁 Loop (repeat until unchecked)",
                value=False,
                key="xrd_loop",
                help="Continuously cycles through the trajectory steps until "
                     "you uncheck this box.",
            )
        with anim_cols[1]:
            delay = st.slider(
                "Frame delay (s)",
                min_value=0.05, max_value=2.0, value=0.20, step=0.05,
                key="xrd_loop_delay",
            )

        if loop:
            # Streamlit-driven animation: draw one frame per rerun, advance the
            # index, then rerun after `delay`. Unchecking the box ends the loop.
            idx = st.session_state.get("xrd_loop_idx", 0) % len(steps)
            placeholder = st.empty()
            placeholder.plotly_chart(
                _single_step_fig(idx), use_container_width=True,
                key="xrd_loop_chart",
            )
            st.caption(f"▶ Looping — showing step {steps[idx]} "
                       f"({idx + 1}/{len(steps)})")
            st.session_state.xrd_loop_idx = idx + 1
            time.sleep(delay)
            _rerun = getattr(st, "rerun", None) or getattr(st, "experimental_rerun")
            _rerun()
        else:
            # Reset the loop counter so the next loop starts from the beginning.
            st.session_state.xrd_loop_idx = 0

            # Plotly native animation: built-in play/pause button + frame slider.
            base_step = steps[0]
            fig = go.Figure(data=[_pattern_trace(0, "Pattern")])
            if overlay_avg:
                fig.add_trace(avg_trace)

            fig.frames = [
                go.Frame(
                    data=[_pattern_trace(idx, "Pattern")],
                    name=str(step),
                    traces=[0],
                )
                for idx, step in enumerate(steps)
            ]

            frame_ms = int(delay * 1000)
            slider_steps = [
                dict(
                    method="animate",
                    args=[
                        [str(step)],
                        dict(
                            mode="immediate",
                            frame=dict(duration=0, redraw=True),
                            transition=dict(duration=0),
                        ),
                    ],
                    label=str(step),
                )
                for step in steps
            ]

            _apply_layout(
                fig,
                f"Powder XRD trajectory animation (start: step {base_step})",
                extra=dict(
                    updatemenus=[
                        dict(
                            type="buttons",
                            showactive=False,
                            x=0.0, y=1.18, xanchor="left",
                            font=dict(size=16),
                            buttons=[
                                dict(
                                    label="▶ Play",
                                    method="animate",
                                    args=[
                                        None,
                                        dict(
                                            frame=dict(duration=frame_ms, redraw=True),
                                            fromcurrent=True,
                                            transition=dict(duration=0),
                                        ),
                                    ],
                                ),
                                dict(
                                    label="⏸ Pause",
                                    method="animate",
                                    args=[
                                        [None],
                                        dict(
                                            frame=dict(duration=0, redraw=False),
                                            mode="immediate",
                                            transition=dict(duration=0),
                                        ),
                                    ],
                                ),
                            ],
                        )
                    ],
                    sliders=[
                        dict(
                            active=0,
                            currentvalue=dict(
                                prefix="Trajectory step: ",
                                font=dict(size=18),
                            ),
                            font=dict(size=15),
                            pad=dict(t=50),
                            steps=slider_steps,
                        )
                    ],
                ),
            )
            st.plotly_chart(fig, use_container_width=True)
            st.caption(
                "Use ▶ Play for a one-shot animation with the step slider, or "
                "tick **Loop** above to repeat continuously until stopped."
            )

    # Average pattern, always available as a static plot + download.
    with st.expander("📊 Average pattern (over all evaluated steps)", expanded=False):
        avg_fig = go.Figure()
        avg_fig.add_trace(
            go.Scatter(
                x=two_theta,
                y=average,
                mode="lines",
                name="Average",
                line=dict(color="#dc2626", width=2),
            )
        )
        avg_fig.update_layout(
            font=base_font,
            title=dict(text="Average powder XRD pattern", font=title_font,
                       x=0.5, xanchor="center"),
            xaxis=dict(title=dict(text="2θ (degrees)", font=axis_title_font),
                       tickfont=tick_font),
            yaxis=dict(title=dict(text=intensity_label, font=axis_title_font),
                       tickfont=tick_font),
            legend=dict(font=legend_font),
            height=460,
            hovermode="x unified",
        )
        st.plotly_chart(avg_fig, use_container_width=True)

        avg_csv = "2theta,intensity\n" + "\n".join(
            f"{x},{y}" for x, y in zip(two_theta, average)
        )
        st.download_button(
            "💾 Download average pattern (.csv)",
            data=avg_csv,
            file_name="average_pattern.csv",
            mime="text/csv",
            key="xrd_download_avg",
        )


# --------------------------------------------------------------------------- #
#  Parameter UI + script generation panel
# --------------------------------------------------------------------------- #
_RADIATION_OPTIONS = [
    "CuKa", "CuKa1", "CuKa2", "CuKb1",
    "MoKa", "MoKa1", "MoKa2", "MoKb1",
    "CrKa", "FeKa", "CoKa", "AgKa",
    "Custom (Å)",
]


def _setup_xrd_trajectory_panel():
    """UI for the XRD-trajectory script: a 'generate script' tab and an
    'output analysis' tab."""
    st.markdown(
        "Compute the **average powder XRD pattern** from an ASE `.xyz` "
        "trajectory and store every individual per-step pattern so you can "
        "scrub through the trajectory or play an animation here. "
        "Pattern maths uses the Rust-accelerated "
        "[`xrd-rust`](https://pypi.org/project/xrd-rust) package."
    )

    tab_gen, tab_out = st.tabs(
        ["📝 Generate standalone script", "📈 Output analysis"]
    )
    with tab_gen:
        _xrd_script_generation_ui()
    with tab_out:
        render_xrd_animation_viewer()


def _xrd_script_generation_ui():
    """Tab 1: pattern parameters + standalone-script generation."""
    st.caption(
        "ℹ️ To run the generated script, install XRD-Rust with "
        "`pip install xrd-rust` (also `ase`, `pymatgen`, `numpy`, and "
        "`matplotlib` for the publication-ready average plot)."
    )

    st.subheader("⚙️ Pattern settings")

    c1, c2, c3 = st.columns(3)
    with c1:
        input_dir = st.text_input(
            "Input folder (scanned for *.xyz)",
            value=".",
            key="xrd_input_dir",
            help="The script processes every `*.xyz` trajectory in this folder, "
                 "writing each one's results to "
                 "`xrd_trajectory_results/<trajectory-name>/`. You can also pass "
                 "a folder or specific files on the command line.",
        )
        stride = st.number_input(
            "Evaluate every Nth step",
            min_value=1,
            value=10,
            step=1,
            key="xrd_stride",
            help="A stride of 10 evaluates trajectory frames 0, 10, 20, 30 … "
                 "and those step numbers are written into the animation file.",
        )
    with c2:
        tt_min = st.number_input(
            "2θ min (°)", min_value=0.0, max_value=179.0,
            value=5.0, step=1.0, key="xrd_tt_min",
        )
        tt_max = st.number_input(
            "2θ max (°)", min_value=1.0, max_value=180.0,
            value=70.0, step=1.0, key="xrd_tt_max",
        )
    with c3:
        radiation = st.selectbox(
            "Wavelength / radiation",
            options=_RADIATION_OPTIONS,
            index=0,
            key="xrd_radiation",
            help="Named X-ray radiation (e.g. CuKa) or a custom wavelength in Å.",
        )
        if radiation == "Custom (Å)":
            wavelength = st.number_input(
                "Custom wavelength (Å)",
                min_value=0.1, max_value=10.0,
                value=1.5406, step=0.0001, format="%.4f",
                key="xrd_custom_wl",
            )
        else:
            wavelength = radiation

    c4, c5, c6 = st.columns(3)
    with c4:
        intensity_mode_label = st.radio(
            "Intensities",
            ["Relative (max = 100)", "Absolute"],
            key="xrd_intensity_mode",
            help="Relative re-normalises each pattern (and the average) so the "
                 "maximum is 100. Absolute keeps the raw calculated intensities.",
        )
        intensity_mode = (
            "relative" if intensity_mode_label.startswith("Relative") else "absolute"
        )
    with c5:
        broaden = st.checkbox(
            "Apply Gaussian peak broadening",
            value=True,
            key="xrd_broaden",
            help="On: each reflection is convolved with a Gaussian onto a "
                 "continuous 2θ grid. Off: the raw discrete peaks are kept and "
                 "the viewer draws them as vertical stick lines.",
        )
        fwhm = st.number_input(
            "Peak broadening FWHM (° 2θ)",
            min_value=0.01, max_value=5.0,
            value=0.10, step=0.01, format="%.2f",
            key="xrd_fwhm",
            disabled=not broaden,
            help="Gaussian width applied to each reflection (only used when "
                 "broadening is enabled).",
        )
    with c6:
        n_points = st.number_input(
            "Grid points (2θ resolution)",
            min_value=200, max_value=20000,
            value=2000, step=100,
            key="xrd_n_points",
            help="Resolution of the common 2θ grid used for broadened profiles "
                 "and for the averaged pattern.",
        )
        num_threads = st.number_input(
            "XRD-Rust threads",
            min_value=1, max_value=64,
            value=4, step=1,
            key="xrd_threads",
        )

    if tt_max <= tt_min:
        st.error("2θ max must be greater than 2θ min.")

    params = {
        "input_dir": input_dir,
        "two_theta_min": tt_min,
        "two_theta_max": tt_max,
        "wavelength": wavelength,
        "intensity_mode": intensity_mode,
        "stride": int(stride),
        "broaden": bool(broaden),
        "fwhm": fwhm,
        "n_points": int(n_points),
        "num_threads": int(num_threads),
    }

    st.divider()
    st.subheader("📝 Generate standalone script")

    if "generated_xrd_traj_script" not in st.session_state:
        st.session_state.generated_xrd_traj_script = None

    if st.button(
        "📝 Generate XRD Trajectory Script (using current settings)",
        key="generate_xrd_traj_script_button",
        type="secondary",
        disabled=tt_max <= tt_min,
    ):
        try:
            st.session_state.generated_xrd_traj_script = (
                generate_xrd_trajectory_script(params)
            )
            st.success("✅ XRD trajectory script generated successfully!")
        except Exception as exc:  # noqa: BLE001
            st.error(f"❌ Failed to generate script: {exc}")
            st.session_state.generated_xrd_traj_script = None

    if st.session_state.generated_xrd_traj_script:
        with st.expander("🐍 View Generated Script", expanded=True):
            st.code(st.session_state.generated_xrd_traj_script, language="python")
            st.download_button(
                label="💾 Download Script (.py)",
                data=st.session_state.generated_xrd_traj_script,
                file_name="run_xrd_trajectory.py",
                mime="text/x-python",
                key="download_xrd_traj_script",
                type="primary",
            )
        st.info(
            "**Instructions:**\n"
            "1. Install XRD-Rust and dependencies: "
            "`pip install xrd-rust ase pymatgen numpy matplotlib`.\n"
            "2. Save the script (e.g. `run_xrd_trajectory.py`).\n"
            "3. Put one or more `.xyz` trajectories in the input folder (frames "
            "must carry a periodic cell — e.g. extended-XYZ MD trajectories).\n"
            "4. Run: `python run_xrd_trajectory.py` (processes every `*.xyz` in "
            "the folder), or pass a folder / specific files as arguments.\n"
            "5. Each trajectory's results land in "
            "`xrd_trajectory_results/<trajectory-name>/`: per-step CSVs, "
            "`average_pattern.csv`, a publication-ready "
            "`average_pattern.png` (+ `.pdf`), and "
            "`xrd_trajectory_animation.json`.\n"
            "6. Open the **📈 Output analysis** tab and upload a trajectory's "
            "`xrd_trajectory_animation.json` to scrub through the steps or play "
            "the animation."
        )


def render_average_structure_viewer():
    """Tab 2: upload an averaged structure file and inspect it (lattice
    parameters, formula, 3-D view)."""
    st.markdown("### 🧊 Inspect an averaged structure")
    st.caption(
        "Upload an `average_structure.*` produced by the generated script "
        "(`.cif`, `.vasp`/`POSCAR`, or extended `.xyz`) to view its averaged "
        "lattice parameters and a 3-D rendering."
    )

    upload = st.file_uploader(
        "Upload an averaged structure file",
        type=["cif", "vasp", "xyz", "poscar"],
        key="avg_struct_upload",
    )
    if upload is None:
        return

    import tempfile
    from ase.io import read as ase_read

    suffix = os.path.splitext(upload.name)[1] or ".xyz"
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb", suffix=suffix, delete=False
        ) as tmp:
            tmp.write(upload.getbuffer())
            tmp_path = tmp.name
        atoms = ase_read(tmp_path)
    except Exception as exc:  # noqa: BLE001
        st.error(f"Could not read the structure file: {exc}")
        return
    finally:
        try:
            os.unlink(tmp_path)
        except (OSError, NameError):
            pass

    cellpar = atoms.cell.cellpar()
    info_cols = st.columns(4)
    info_cols[0].metric("Atoms", f"{len(atoms)}")
    info_cols[1].metric("Formula", atoms.get_chemical_formula("hill"))
    info_cols[2].metric("Volume (Å³)", f"{atoms.get_volume():.2f}")
    info_cols[3].metric("Cell rank", f"{atoms.cell.rank}")

    lat_cols = st.columns(6)
    for col, lab, val in zip(
        lat_cols,
        ["a (Å)", "b (Å)", "c (Å)", "α (°)", "β (°)", "γ (°)"],
        cellpar,
    ):
        col.metric(lab, f"{val:.4f}")

    try:
        from pymatgen.io.ase import AseAtomsAdaptor
        from helpers.structure_preview import view_structure

        structure = AseAtomsAdaptor().get_structure(atoms)
        st.iframe(view_structure(structure, height=420, width=620), height=440)
    except Exception as exc:  # noqa: BLE001
        st.info(f"3-D preview unavailable ({exc}). Lattice data shown above.")


def _setup_average_structure_panel():
    """UI for the average-structure script: a 'generate script' tab and an
    'output analysis' tab."""
    st.markdown(
        "Compute the **PBC-aware average structure** from every `.xyz` "
        "trajectory in a folder. The lattice parameters are averaged and the "
        "atomic positions are averaged with a periodic (circular) mean of the "
        "fractional coordinates, so atoms crossing a cell boundary are handled "
        "correctly; atoms are then wrapped back inside the averaged cell."
    )

    tab_gen, tab_out = st.tabs(
        ["📝 Generate standalone script", "🧊 Output analysis"]
    )
    with tab_gen:
        _avg_structure_generation_ui()
    with tab_out:
        render_average_structure_viewer()


def _avg_structure_generation_ui():
    """Tab 1: averaging parameters + standalone-script generation."""
    st.caption(
        "ℹ️ To run the generated script, install ASE and NumPy with "
        "`pip install ase numpy`."
    )

    st.subheader("⚙️ Averaging settings")

    c1, c2, c3 = st.columns(3)
    with c1:
        input_dir = st.text_input(
            "Input folder (scanned for *.xyz)",
            value=".",
            key="avg_input_dir",
            help="The script processes every `*.xyz` trajectory in this folder, "
                 "writing each one's average structure to "
                 "`average_structure_results/<trajectory-name>/`. You can also "
                 "pass a folder or specific files on the command line.",
        )
    with c2:
        stride = st.number_input(
            "Average every Nth frame",
            min_value=1, value=1, step=1,
            key="avg_stride",
            help="Use every frame (1) or sub-sample the trajectory.",
        )
    with c3:
        skip_initial = st.number_input(
            "Skip first N frames (equilibration)",
            min_value=0, value=0, step=1,
            key="avg_skip_initial",
            help="Discard initial non-equilibrated frames before averaging.",
        )

    c4, c5 = st.columns([1, 2])
    with c4:
        wrap = st.checkbox(
            "Wrap atoms into cell (PBC)",
            value=True,
            key="avg_wrap",
            help="Wrap every averaged atom back inside the averaged cell.",
        )
    with c5:
        fmt_labels = st.multiselect(
            "Output structure formats",
            options=["CIF (.cif)", "VASP (POSCAR/.vasp)", "Extended XYZ (.xyz)"],
            default=["CIF (.cif)", "VASP (POSCAR/.vasp)", "Extended XYZ (.xyz)"],
            key="avg_formats",
            help="The averaged structure is written in each selected format.",
        )
    fmt_map = {
        "CIF (.cif)": "cif",
        "VASP (POSCAR/.vasp)": "vasp",
        "Extended XYZ (.xyz)": "xyz",
    }
    formats = [fmt_map[f] for f in fmt_labels] or ["cif"]

    params = {
        "input_dir": input_dir,
        "stride": int(stride),
        "skip_initial": int(skip_initial),
        "wrap": bool(wrap),
        "formats": formats,
    }

    st.divider()
    st.subheader("📝 Generate standalone script")

    if "generated_avg_structure_script" not in st.session_state:
        st.session_state.generated_avg_structure_script = None

    if st.button(
        "📝 Generate Average Structure Script (using current settings)",
        key="generate_avg_structure_script_button",
        type="secondary",
    ):
        try:
            st.session_state.generated_avg_structure_script = (
                generate_average_structure_script(params)
            )
            st.success("✅ Average structure script generated successfully!")
        except Exception as exc:  # noqa: BLE001
            st.error(f"❌ Failed to generate script: {exc}")
            st.session_state.generated_avg_structure_script = None

    if st.session_state.generated_avg_structure_script:
        with st.expander("🐍 View Generated Script", expanded=True):
            st.code(st.session_state.generated_avg_structure_script,
                    language="python")
            st.download_button(
                label="💾 Download Script (.py)",
                data=st.session_state.generated_avg_structure_script,
                file_name="run_average_structure.py",
                mime="text/x-python",
                key="download_avg_structure_script",
                type="primary",
            )
        st.info(
            "**Instructions:**\n"
            "1. Install dependencies: `pip install ase numpy`.\n"
            "2. Save the script (e.g. `run_average_structure.py`).\n"
            "3. Put one or more `.xyz` trajectories in the input folder (frames "
            "must carry a periodic cell — e.g. extended-XYZ MD trajectories).\n"
            "4. Run: `python run_average_structure.py` (processes every `*.xyz` "
            "in the folder), or pass a folder / specific files as arguments.\n"
            "5. Each trajectory's results land in "
            "`average_structure_results/<trajectory-name>/`: the averaged "
            "structure file(s) and `average_lattice.txt`.\n"
            "6. Open the **🧊 Output analysis** tab and upload an "
            "`average_structure.*` file to inspect its lattice and 3-D view."
        )


def render_postprocessing_panel():
    """Top-level entry: choose a post-processing script and render its panel."""
    st.subheader("🧪 Selected postprocessing scripts")
    st.markdown(
        "Generate a self-contained Python analysis script to run on your own "
        "machine, then upload its result file here to explore it interactively."
    )

    script_choice = st.selectbox(
        "Choose a postprocessing script",
        options=POSTPROCESSING_SCRIPTS,
        index=0,
        key="postprocessing_script_choice",
    )

    st.divider()

    if script_choice == XRD_TRAJECTORY_SCRIPT:
        _setup_xrd_trajectory_panel()
    elif script_choice == AVERAGE_STRUCTURE_SCRIPT:
        _setup_average_structure_panel()
    else:
        st.info("This script is not available yet.")
